error func main() {
	try {Tracker* t = initTracker()}
	catch (e) {
		eprintln("Failed to init tracker. Error code %d", e);
		popupBox("Failed to init tracker", e);
	}

	// Is `t` available in this scope? It feels like it should be for making code clean but also not cause its in a code block
}

error func initTracker() -> Tracker* {
	propagate Tracker *t = malloc(sizeof(Tracker));
	t.is_captain = true;
	propagate initMapCache(t);
}

error func initMapCache(tracker: Tracker*) {
	propagate 
}